### ISSUE TITLE
运行错误， java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by hgxfg9** [testerSunshine/ddmc#1]
12:02:04: 数据初始化中
12:02:05: 数据初始化完成
12:02:05: 加载购物车商品
12:02:07: 加载购物车完成
12:02:07: 加载购物车商品
12:02:10: 当前无可用配送时间
12:02:10: 当前无可用配送时间
12:02:10: 加载购物车完成
12:02:10: 加载购物车商品
12:02:10: 当前无可用配送时间
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
12:02:11: 错误, java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by testerSunshine** [comment]
能截图看看你的配置嘛？

**Comment by hgxfg9** [comment]
![image](https://user-images.githubusercontent.com/36105145/163105319-8564a4fe-61dc-4aa1-823a-d45e0ee15ba6.png)
麻烦看一下

**Comment by testerSunshine** [comment]
不要勾选test，把下单线程改成1，一样能测试，这个问题我下个版本修复掉

**Comment by hgxfg9** [comment]
![image](https://user-images.githubusercontent.com/36105145/163109746-f06abda0-5b75-448d-8a6e-5d0dc71da051.png)

程序好像还存在内存溢出的情况，会卡死然后内存占用一直上涨

**Comment by hgxfg9** [comment]
> ![image](https://user-images.githubusercontent.com/36105145/163109746-f06abda0-5b75-448d-8a6e-5d0dc71da051.png)
> 
> 程序好像还存在内存溢出的情况，会卡死然后内存占用一直上涨

经测试，不勾选TEST的情况下也是会出现一样的报错

**Comment by testerSunshine** [comment]
> > ![image](https://user-images.githubusercontent.com/36105145/163109746-f06abda0-5b75-448d-8a6e-5d0dc71da051.png)
> > 程序好像还存在内存溢出的情况，会卡死然后内存占用一直上涨
> 
> 经测试，不勾选TEST的情况下也是会出现一样的报错

可能是因为报错引起的线程没关闭
