### ISSUE TITLE
强烈要求增加通知比如Bark 或者能不能打包成一个docker 在服务器上运行啊

### ISSUE THREAD

**Issue by JONREAN2** [testerSunshine/ddmc#3]
感谢大佬

**Comment by gdracula** [comment]
或者server酱，bark安卓不好用，谢谢大佬

**Comment by testerSunshine** [comment]
https://gitee.com/wenxiansen/ddmc-gui/releases/041401

**Comment by testerSunshine** [comment]
有提醒了，给你放好日子.mp3，hh

**Comment by testerSunshine** [comment]
server酱收费了，可以换个别的微信通知你，晚点我加下，另外docker其实没必要吧，大部分人都不会用
