### ISSUE TITLE
1】提醒音乐没声音 2】开始时间未生效

### ISSUE THREAD

**Issue by oiin** [testerSunshine/ddmc#5]
程序亲测有效，今天刚使用，一会就捡漏成功，大赞！！！
美中不足
1】提醒音乐没声音，戴耳机试，也没声音。

有个问题
1】直接预约的间隔时间是多少？能否增加自定义间隔时间的功能？

**Comment by oiin** [comment]
![image](https://user-images.githubusercontent.com/88411797/163660303-9503c15f-df21-494f-acd8-4544fc39e1e5.png)

**Comment by oiin** [comment]
问题2】能否在直接预约定时启动后，设置x分钟后自动切换到捡漏模式？
例如：5点59分50秒启动直接预约，设置2分钟后切换到捡漏模式

**Comment by testerSunshine** [comment]
语音问题修复了
https://github.com/testerSunshine/ddmc/releases/tag/041603

**Comment by testerSunshine** [comment]
> 程序亲测有效，今天刚使用，一会就捡漏成功，大赞！！！ 美中不足 1】提醒音乐没声音，戴耳机试，也没声音。
> 
> 有个问题 1】直接预约的间隔时间是多少？能否增加自定义间隔时间的功能？

直接预约不支持手动设置，目前都是100ms

**Comment by testerSunshine** [comment]
> 问题2】能否在直接预约定时启动后，设置x分钟后自动切换到捡漏模式？ 例如：5点59分50秒启动直接预约，设置2分钟后切换到捡漏模式

这个功能我觉得没必要，两分钟后人反正是在电脑前，所以自己切换一下成本也比较小

**Comment by oiin** [comment]
提示音乐没声音的问题，已解决 ！！！
使用新版本过程中发现新问题
1】开始时间设置好之后，没有生效，点击预约按钮，程序就直接启动了

**Comment by testerSunshine** [comment]
> 提示音乐没声音的问题，已解决 ！！！ 使用新版本过程中发现新问题 1】开始时间设置好之后，没有生效，点击预约按钮，程序就直接启动了

这个不是启动时间，是下单时间，仔细看说明

**Comment by oiin** [comment]
受教了，谢谢大佬！！！
